name: CI NPM Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  npm-test:
    name: NPM Package Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install --no-optional

    - name: Check package syntax
      run: |
        node -e "console.log('Node.js syntax OK')"
        
    - name: Test package installation
      run: |
        npm pack
        npm install -g ./crawl4ai-mcp-sse-stdio-*.tgz
        
    - name: Basic functionality test
      run: |
        which crawl4ai-mcp || echo "Command not found in PATH, checking npx"
        npx crawl4ai-mcp --help || echo "Help command test completed"
