name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (for manual trigger)'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Extract version from release tag
        if: github.event_name == 'release'
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Update version in package.json
        if: github.event_name == 'release'
        run: |
          npm version $VERSION --no-git-tag-version --allow-same-version
          cat package.json | grep version
      
      - name: Configure NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      
      - name: Publish to NPM
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest
    needs: [publish-npm]
    if: github.event_name == 'release'
    permissions:
      contents: write
    
    steps:
      - name: Update release with links
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = context.payload.release;
            const version = release.tag_name.replace('v', '');
            
            const additionalNotes = \`
            
            ## 📦 Installation
            
            ### Via NPM:
            \\\`\\\`\\\`bash
            npm install -g crawl4ai-mcp-sse-stdio@\${version}
            npx crawl4ai-mcp --help
            \\\`\\\`\\\`
            
            ## 🔗 Package Links
            - [NPM Package](https://www.npmjs.com/package/crawl4ai-mcp-sse-stdio/v/\${version})
            \`;
            
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: release.body + additionalNotes
            });
