name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run security scan with Bandit
      uses: PyCQA/bandit-action@v1
      with:
        targets: crawl4ai_mcp

    - name: Scan for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD

  type-checking:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Python dependencies
      run: |
        pip install -e .
        pip install mypy types-requests

    - name: Install Node dependencies
      run: |
        npm install

    - name: Run Python type checking (mypy)
      run: |
        mypy crawl4ai_mcp --ignore-missing-imports

    - name: Run TypeScript type checking
      run: |
        echo "TypeScript type checking skipped - no TypeScript in current project"

  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check README exists
      run: |
        test -f README.md
        echo "Single-repo structure - main README.md exists"

    - name: Check documentation completeness
      run: |
        grep -qi "Installation" README.md
        grep -qi "Usage" README.md
        grep -qi "Configuration" README.md

    - name: Validate JSON files
      run: |
        python -m json.tool server-config.example.json > /dev/null
        find . -name "*.json" -exec python -m json.tool {} \; > /dev/null

    - name: Check Dockerfile best practices
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3008